export const ASYNC_ADD_NAV_TAG = 'ASYNC_ADD_NAV_TAG'
export const SYNC_CHANGE_TIME = 'SYNC_CHANGE_TIME'
export const SET_CURRENT_ROUTE = '设置当前页面的路由'
export const TOGGLE_LANGUAGE = 'TOGGLE_LANGUAGE'
export const CHANGE_PROJECT = 'CHANGE_PROJECT'
export const SET_CURRENT_TEAM_ID = 'SET_CURRENT_TEAM_ID'
export const SET_CURRENT_USER_ID = 'SET_CURRENT_USER_ID'
export default {
  ASYNC_ADD_NAV_TAG,
  SYNC_CHANGE_TIME,
  SET_CURRENT_ROUTE,
  TOGGLE_LANGUAGE,
  CHANGE_PROJECT,
  SET_CURRENT_TEAM_ID,
  SET_CURRENT_USER_ID,
}
